### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by AydinHassan** [php-school/learn-you-php#4]

**Comment by AydinHassan** [comment]
<img width="969" alt="screen shot 2015-10-23 at 19 43 45" src="https://cloud.githubusercontent.com/assets/2817002/10701960/81894324-79be-11e5-8295-203f73939942.png">

**Comment by mikeymike** [comment]
<img width="498" alt="screen shot 2016-02-01 at 22 56 17-lpqbj8s2by" src="https://cloud.githubusercontent.com/assets/2174476/12734228/2bb56e46-c937-11e5-803a-e94687adfbce.png">
