### ISSUE TITLE
MyFirstIo solution output

### ISSUE THREAD

**Issue by adam-paterson** [php-school/learn-you-php#44]
It's only minor, but the solution for [My First IO](https://github.com/php-school/learn-you-php/blob/master/exercises/my-first-io/solution/solution.php#L4) contains an escaped character which escapes in the terminal output too.

**Comment by AydinHassan** [comment]
Is this the "\n" ? https://github.com/php-school/php-workshop/issues/80 ?

We have to override the php-parser pretty printer to fix this. Last time I tried I broke loads of tests, definitely needs fixing though, just requires a bit more effort :(

**Comment by adam-paterson** [comment]
Yeah, that's the one. I've played around too but broke the tests as well.
