### ISSUE TITLE
Fatal error in installing

### ISSUE THREAD

**Issue by sdavara** [php-school/learn-you-php#45]
When I try to run "composer global require php-school/learn-you-php" I get below error. My php version is 5.6.17

PHP Fatal error:  Class 'Composer\Installer\PackageEvents' not found in /Users/shailesh/.composer/vendor/php-school/workshop-installer/src/Plugin.php on line 42

**Comment by mikeymike** [comment]
Hi @sdavara 

what version of Composer are you running ? Could you try a `composer self-update` and then the install again to see if it's an outdated version of Composer causing the problem.

**Comment by sdavara** [comment]
Thanks @mikeymike. It worked for me
