### ISSUE TITLE
Translating to Brasilian Portuguese 

### ISSUE THREAD

**Issue by osvaldoabel** [php-school/learn-you-php#46]
I'd like to translate it to Brasilian Portuguese. 
what do you think , if we change a bit this folder structure ? 
- /
  - src /
    -  en/
      - exercices /
    - pt-br/
      - exercícios /

it will be more easy to contribute with another languages

**Comment by AydinHassan** [comment]
Yes we will very much support multi-language in the future, but there would be a fair amount of work to do to support this. We would need to build in a way to select the language then we would also have to modify https://github.com/php-school/php-workshop to select the proper solution/problem based on the selected language. 

We probably won't be able to support this for some time yet, there is still lots of things to do!

**Comment by osvaldoabel** [comment]
ok @AydinHassan 
i'd like to contribute with anything. i'm studying the code source and i hope to some great feature to add on.

**Comment by AydinHassan** [comment]
Awesome, well priorities right now are documentation and improvements to the website, we feel it is important to ease the user and provide lots of information so people can build their own workshops, then we will take a look at adding new features :smile:

**Comment by AydinHassan** [comment]
I guess the starting point to this would be to build a menu where user can select language into  https://github.com/php-school/php-workshop and it be saved alongside the user's progress.

Later tonight I will create some issues of the steps I think we need to take to make this happen and create a milestone, maybe some people can jump on and help with little bits :)

**Comment by AydinHassan** [comment]
@Kanguanda I added some issues here: https://github.com/php-school/php-workshop/milestones/Multi%20Language%20Support. We can track it there, I will close this for now :smile:
