### ISSUE TITLE
Question on Ex10

### ISSUE THREAD

**Issue by devnuhl** [php-school/learn-you-php#50]
Is it supposed to be looking at www.time.com, rather than running a web server request on the exercise file? I've glanced through the code, as well as poured over the instructions for the exercise and I'm not seeing where you're supposed to configure anything for the HTTP server that we're implementing. 

Not clear if we're supposed to supply a domain to the script, or if that's supposed to be part of the run/verify scripts.

**Comment by AydinHassan** [comment]
You do not configure anything, we invoke your solution as if it is behind a http server. So your script just needs to act on the get/post data and respond/echo out a response.

Is the documentation lacking?

**Comment by devnuhl** [comment]
That was how I read the documentation, but I am receiving shell errors when it is trying to load `URL:     http://www.time.com/api/parsetime?iso=2016-02-12T16:00:25+0000`

`sh: 1: -dalways_populate_raw_post_data=-1: not found
sh: echo: I/O error`

Does not seem to relate to anything in my script. That is from the `run` output. The `verify` output says there is an error while invoking the map callback in CgiRunner, then fatal error:

`
PHP Fatal error:  Uncaught exception 'PhpSchool\PhpWorkshop\Exception\SolutionExecutionException' with message 'PHP Code failed to execute. Error: "sh: 1: -dalways_populate_raw_post_data=-1: not found
sh: echo: I/O error
"' in /home/entropy/.composer/vendor/php-school/php-workshop/src/ExerciseRunner/CgiRunner.php:74
`

**Comment by AydinHassan** [comment]
Interesting. Looks like the php-cgi binary could not be found. What is your setup? i'll see if I can reproduce

**Comment by devnuhl** [comment]
Might be the php7 install from ondrej's ppa, then. I noticed that wasn't showing in the installed packages, but thought it might've been rolled into something else.

**Comment by AydinHassan** [comment]
I assumed the cgi binary is always available, ill do some investigating but im away this weekend so wont be until next week. Sorry for the inconvenience 😞

**Comment by devnuhl** [comment]
That's fine, @AydinHassan. I'll try running the same code I have on a php5.6 installation, making sure the binary is there. Definitely seems like it might be the culprit.

```
entropy@chris-VirtualBox:~/sf_Dev/php$ apt-cache search php5|grep cgi
php5-cgi - server-side, HTML-embedded scripting language (CGI binary)
php5-mapscript - php5-cgi module for MapServer
entropy@chris-VirtualBox:~/sf_Dev/php$ apt-cache search php7|grep cgi
entropy@chris-VirtualBox:~/sf_Dev/php$ 
```

**Comment by AydinHassan** [comment]
@devnuhl did you get chance to run on 5.6? Also could you try installed install the PHP7 cgi module? I think it is `php7.0-cgi` I think the only thing we can do is show a better error message if the cgi binary cannot be found

**Comment by devnuhl** [comment]
I did not get a chance to test it yet. Forgot what the weekend was. *buntu
14.04 doesn't support 7 on its own, and ondrej who made php7 ppas does not
seem to have made the php7-cgi. I had already checked. Can try on a
newer/different Linux OS version as well.

I have also noticed the poor error when installing the project via composer
with 14.04, since it doesn't have packages for 5.6, either that it says
there is no package meeting minimum stability requirements, rather than
that I don't have hr minimum PHP version.

**Comment by AydinHassan** [comment]
@devnuhl I just tried on a fresh Ubuntu VM with ondrej's ppa. You are right it didn't work at first with the default `php7.0` package. I then installed `php7.0-cgi` with `sudo apt-get install php7.0-cgi` and it worked.

Now I suppose we should add a message about that, maybe die on bootsrap if the cgi binary doesn't exist and provide some recommendations. I don't think it is a package we can define as a dependency with Composer.

Also the error you mentioned about `PHP 5.6` has been fixed a while ago with a more robust install command, this is live on the site now.

**Comment by devnuhl** [comment]
That would explain why it wouldn't work, I wasn't finding the cgi when searching apt, and was trying php7-cgi. I just installed 5.6 and it worked with the cgi (which was not included by default when installing 5.6 via the ppa, either. So it may be worth a message about the cgi package being required if it's not found, since I think under normal circumstances it is included when php is installed.

Strange that I didn't see the error in the latter half of last week with regard to the installation via composer. Now I just have two challenges left, and then to start looking into what I might need to do to get this working on windows ;)

**Comment by AydinHassan** [comment]
@devnuhl I would like to keep this open, while I figure out a way to provide a better message :) the cgi binary doesn't seem to be named the same way so I'm trying to investigate :)

**Comment by devnuhl** [comment]
Apologies. I looked back at my original question, and that had been
resolved. Forgot that we had something else pop up in the middle that was
going to be worked on.

**Comment by AydinHassan** [comment]
@devnuhl we added instructions to get it running on Windows http://www.phpschool.io/install/

**Comment by devnuhl** [comment]
I suppose that would be one way to do it. I was planning to experiment with getting it to run natively, though. In the mean time, the above would definitely help, and I know a few people who will appreciate the instructions. I will be sharing it with them. Thanks.

**Comment by mikeymike** [comment]
@devnuhl we'd love help on getting this working natively. We hit a few brick walls with PHP and it's support for Windows CMD. Also we found by using Cygwin we can easily get all the PHP packages required, which is a big bonus for a simple installation.  

I read somewhere (can't find the link anymore :disappointed: ) that Windows will be getting ASCII and VT100 support soon, so if that drops we might finally get some limited native support :+1:

**Comment by devnuhl** [comment]
@mikeymike I'm wondering if Powershell might be to what is being referred. I managed to get an installation to finalize, though I had forgotten to give it a proper target path for windows, and it defaulted to the Linux path. But composer came back with the following:

```
The directory: /usr/local/bin is not writeable. The workshop learnyouphp cannot be installed.
You have two options now:
 1. Add the composer global bin dir: C:\dev/vendor/bin to your PATH variable
 2. Run learnyouphp directly with C:\dev/vendor/bin/learnyouphp
```

The problem I'm running into now, I think is related to the script itself, which is trying to rely on `sh` from the environment path, and then checking for cygpath. Running the file directly, i'm finding a lot of things for windows simply haven't been implemented yet (and how i might implement them).

**Comment by mikeymike** [comment]
hey @devnuhl your right a lot of the features we painstakingly found out just are not possible with PHP. Well they are but just not at this high level, it would require lower level code such as `Ncurses` but unfortunately this isn't bundle by default with PHP and at this point there doesn't seem to be a simple way (like Composer) to require PHP extensions. 

If you have any ideas or anything though we can talk about them in [CLI Menu Windows Issue](https://github.com/php-school/cli-menu/issues/6) :smile:

**Comment by devnuhl** [comment]
And then bash on Windows is announced. It shouldn't be long now til it can run on windows, though people may need to setup that small piece of it. Not sure if it will be enabled by default when it officially rolls.
