### ISSUE TITLE
Ex8: PDOException if no php5-sqlite installed

### ISSUE THREAD

**Issue by snay** [php-school/learn-you-php#51]
For exercise №8 "Database Read" package php5-sqlite should be installed on Ubuntu.
Without it the runner and verifier will throw **PDOException with message 'could not find driver'**. 
I guess, this is not by design and should be mentioned in requirements or hints.
Also, after installation of missing packages and running _learnyouphp run <filename>_ again, the **RuntimeException with message 'Database directory /tmp/... already exists'** throwed.
Deleting of mentioned folder of course helps.

**Comment by AydinHassan** [comment]
Thanks for reporting @snay. Maybe you could send a pr to add `php5-sqlite` to composer requirements? if not i'll take a look later.

**Comment by snay** [comment]
I'm not too familiar with composer, but it looks to be the only solution: if we require ext-pdo_sqlite there will be the message.

>   Problem 1
>     - The requested PHP extension ext-pdo_sqlite \* is missing from your system. Install or enable PHP's pdo_sqlite extension.

Rather clear for me, but is it ok from usability view and so?

**Comment by AydinHassan** [comment]
That is okay for me, if it proves to be troublesome we can add something to the website install guide (should be ready soon)

**Comment by AydinHassan** [comment]
I've created a PR to do the cleaning up here: https://github.com/php-school/php-workshop/pull/99
