### ISSUE TITLE
can't navigate menu

### ISSUE THREAD

**Issue by twmbx** [php-school/learn-you-php#54]
using elementary os, fish shell, php-fpm 7.0.3

cannot navigate learnyouphp menu.
seems completely unresponsive except to the "enter" key.
as such, I'm stuck on hello world

**Comment by mikeymike** [comment]
Hey @twoSeats thanks for reporting this.

We'll have to spin up a virtual machine to test this. Could you try using bash rather than fish to narrow the issue down a little.

**Comment by mikeymike** [comment]
Also this is likely an issue with php-school/cli-menu package so we'll set up an issue on there too.

**Comment by twmbx** [comment]
hey @mikeymike sorry, meant to mention that i did try it out in bash, didn't work.
I have found however that it's working perfectly fine after a reboot.
odd indeed. I did terminate my shell and try again to no avail originally.

But good thing is, it is working.

Maybe a troubleshooting note is required in the readme, just in case.

**Comment by mikeymike** [comment]
Great news! I'll close this for now but if it ever pops up again don't hesitate to reopen it and we can look into in more detail
