### ISSUE TITLE
[DomainException] windows is not supported

### ISSUE THREAD

**Issue by jnasoy** [php-school/learn-you-php#62]
I followede all the instructions here : https://www.phpschool.io/install#windows, but still i got [DomainException] windows is not supported error. any suggestion?

**Comment by AydinHassan** [comment]
Hi @indongsaeng could you maybe show the whole stack trace you received?

**Comment by jnasoy** [comment]
Hello @AydinHassan , please take a look at the screenshot
![phpschool](https://cloud.githubusercontent.com/assets/7227288/17388807/2a17b860-5a31-11e6-9052-d9780079bcd8.png)

**Comment by AydinHassan** [comment]
That is very strange, unfortunately I don't have a windows machine to investigate. @mikeymike any ideas? You could check out the docker version here: https://github.com/php-school/docker-phpschool created by @rafaelstz !

**Comment by mikeymike** [comment]
Hmmm strange indeed. @indongsaeng are you certain that `Cygwin Bash` is selected within your ConEmu preferences. 

If that's not it could it be that the PHP it's using is the Windows binary and not the one installed through Cygwin ? 

If it's none of these I'm pretty stumped 😕

**Comment by AydinHassan** [comment]
We don't recommend running on windows natively any more - @mikeymike has been working hard on the docker side - so if you are still having trouble, head over to https://github.com/php-school/docker-phpschool and follow the instructions there :)

We will be updating the installation instructions on the website soon.
