### ISSUE TITLE
Create more friendly "fail" messages

### ISSUE THREAD

**Issue by pavlakis** [php-school/learn-you-php#66]
These are suggestions for new users.
- Avoid the use of `Fail!`
- Offer some encouragement. e.g.  you did so and so correct. Try line number xx...

**Comment by AydinHassan** [comment]
The output does say underneath `Your solution to Hello World didn't pass. Try again!` which is a bit nicer, can you think of a nicer word than `Fail!` ?

Second one is a bit trickier but I'm sure we could do something.
