### ISSUE TITLE
User experience with getting started

### ISSUE THREAD

**Issue by pavlakis** [php-school/learn-you-php#67]
This is for new users in the command line.

In Exercise 1, you display the following info:

```

You can write to the console like so:

    <?php

    echo "text";

```

That is a bit confusing to people using the command line for the first time. Give some information on:
- creating a file using their favourite editor (maybe even list a number of editors depending on OS).
- show the directory location
- might want to create the file initially - at least for the 1st exercise

**Comment by AydinHassan** [comment]
Fixed with #70
