### ISSUE TITLE
Hoa\Socket 1.0 has been released

### ISSUE THREAD

**Issue by Hywan** [php-school/learn-you-php#68]
Hello 😃,

Thanks for using [`Hoa\Socket`](https://github.com/hoaproject/Socket)!
I don't know if you are aware but the 1.0 version has been released! We really recommend to upgrade to this version if possible. We can help you to migrate too (see the `README.md` to get help).

**Comment by AydinHassan** [comment]
hey, will put this on the list of things to do :D
