### ISSUE TITLE
Class 'ZipArchive' not found when try to install learnyouphp

### ISSUE THREAD

**Issue by silviuvoicu** [php-school/learn-you-php#71]
Hi,

I have installed and I verify that everything is ok with workshop-manager in my machine with ubuntu and php 7.0.12 but when I tried to install learnyouphp I got this error: 
 
PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in phar:///usr/local/bin/workshop-manager/src/Installer/Installer.php:136

**Comment by AydinHassan** [comment]
Sorry about the delay I've been away for the weekend.

Hmm, that's strange. We check that that extension is installed in the verify command on: https://github.com/php-school/workshop-manager/blob/master/src/Command/VerifyInstall.php#L87

Which version of Ubuntu and workshop-manager are you using?

`workshop-manager -V`

**Comment by silviuvoicu** [comment]
Hey, no problem.

 workshop-manager -V
PHP School Workshop Manager dev-bb4208ce3e0193ced6b2e1cf11a81562a9c9f790@bb4208ce3e0193ced6b2e1cf11a81562a9c9f790

I use ubuntu 16.04 kernel 4.4.0-45-generic x86_64.

The verify command say everything is ok, but again when try to install learnyouphp I still have an error:

 workshop-manager install learnyouphp

PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in phar:///usr/local/bin/workshop-manager/src/Installer/Installer.php:136
Stack trace:
#0 phar:///usr/local/bin/workshop-manager/src/Command/InstallWorkshop.php(43): PhpSchool\WorkshopManager\Installer\Installer->installWorkshop(Object(PhpSchool\WorkshopManager\Entity\Workshop))
#1 [internal function]: PhpSchool\WorkshopManager\Command\InstallWorkshop->__invoke(Object(Symfony\Component\Console\Output\ConsoleOutput), 'learnyouphp')
#2 phar:///usr/local/bin/workshop-manager/vendor/php-di/invoker/src/Invoker.php(82): call_user_func_array(Object(PhpSchool\WorkshopManager\Command\InstallWorkshop), Array)
#3 phar:///usr/local/bin/workshop-manager/vendor/mnapoli/silly/src/Application.php(80): Invoker\Invoker->call(Object(PhpSchool\WorkshopManager\Command\InstallWorkshop), Array)
#4 [internal function]: Silly\Application->Silly{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///usr/local/bin/works in phar:///usr/local/bin/workshop-manager/src/Installer/Installer.php on line 136

Fatal error: Uncaught Error: Class 'ZipArchive' not found in phar:///usr/local/bin/workshop-manager/src/Installer/Installer.php on line 136

Error: Class 'ZipArchive' not found in phar:///usr/local/bin/workshop-manager/src/Installer/Installer.php on line 136

Call Stack:
    0.0691     361736   1. {main}() /usr/local/bin/workshop-manager:0
    0.1978     976752   2. require('phar:///usr/local/bin/workshop-manager/bin/workshop-manager') /usr/local/bin/workshop-manager:11
    0.1980     989888   3. require('phar:///usr/local/bin/workshop-manager/app/bootstrap.php') phar:///usr/local/bin/workshop-manager/bin/workshop-manager:3
    0.3765    2549568   4. Symfony\Component\Console\Application->run() phar:///usr/local/bin/workshop-manager/app/bootstrap.php:49
    0.3962    2786088   5. Symfony\Component\Console\Application->doRun() phar:///usr/local/bin/workshop-manager/vendor/symfony/console/Application.php:118
    0.3965    2786088   6. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/bin/workshop-manager/vendor/symfony/console/Application.php:187
    0.3965    2786088   7. Symfony\Component\Console\Command\Command->run() phar:///usr/local/bin/workshop-manager/vendor/symfony/console/Application.php:824
    0.3975    2788344   8. call_user_func:{phar:///usr/local/bin/workshop-manager/vendor/symfony/console/Command/Command.php:254}() phar:///usr/local/bin/workshop-manager/vendor/symfony/console/Command/Command.php:254
    0.3975    2788344   9. Silly\Application->Silly{closure}() phar:///usr/local/bin/workshop-manager/vendor/symfony/console/Command/Command.php:254
    0.3976    2789040  10. Invoker\Invoker->call() phar:///usr/local/bin/workshop-manager/vendor/mnapoli/silly/src/Application.php:80
    0.7811    3915256  11. call_user_func_array:{phar:///usr/local/bin/workshop-manager/vendor/php-di/invoker/src/Invoker.php:82}() phar:///usr/local/bin/workshop-manager/vendor/php-di/invoker/src/Invoker.php:82
    0.7811    3915664  12. PhpSchool\WorkshopManager\Command\InstallWorkshop->__invoke() phar:///usr/local/bin/workshop-manager/vendor/php-di/invoker/src/Invoker.php:82
    0.7813    3915664  13. PhpSchool\WorkshopManager\Installer\Installer->installWorkshop() phar:///usr/local/bin/workshop-manager/src/Command/InstallWorkshop.php:43

**Comment by AydinHassan** [comment]
Ah, looks like you are using a version before the extension checks were added. You should be able to update with `workshop-manager self-update` if you installed via phar. Then hopefully verify should give you a better error message.

**Comment by silviuvoicu** [comment]
I try workshop-manager self-update, but there's no need for an upgrade

sudo workshop-manager self-update
[sudo] password for silviu: 

No update necessary!

I have installed like this:

curl -O https://php-school.github.io/workshop-manager/workshop-manager.phar
mv workshop-manager.phar /usr/local/bin/workshop-manager
chmod +x /usr/local/bin/workshop-manager
workshop-manager verify

But the only difference is that for moving to /usr/local/bin I need to do sudo first, and verify say everything is ok.

**Comment by AydinHassan** [comment]
seems like the phar building is broke 😞 , will take a look shortly

**Comment by AydinHassan** [comment]
@silviuvoicu I think I fixed the build process. Basically new phars wern't getting uploaded. You should be able to update to latest workshop-manager now. Then you should see error in verify command.

Then you can install zip extension and everything should work 😄 

Let me know how it goes!

**Comment by silviuvoicu** [comment]
Thank you.
Now it works. I have been able to install the workshops, but I have a suggestion so for the find/search for workshop-manager, that if I don't provide a term to search to give me all possible workshops and not complaining that there is no search parameter, but that's another matter.
Again, thank you very much.

**Comment by AydinHassan** [comment]
Thats a great idea, would you like to havea go? If not I can take a look!
