### ISSUE TITLE
No workshops found matching "learnyouphp", did you spell it correctly?

### ISSUE THREAD

**Issue by naltun** [php-school/learn-you-php#73]
When I go to `workshop-manager install learnyouphp` I get the error message in the title.

I also get the following warnings `Notice: Use of undefined constant ARRAY_FILTER_USE_BOTH - assumed 'ARRAY_FILTER_USE_BOTH'` and `Warning: array_filter() expects at most 2 parameters, 3 given in phar://...` before the final error message.

**Comment by AydinHassan** [comment]
Hey @naltun sounds like you are using an old PHP version. We require at least 5.6. Do you know what version you are using?

**Comment by naltun** [comment]
I was using 5.5.9, thinking I was using 5.6. Apologies @AydinHassan 
I ran the installation on a 7.x box, and it worked. Thanks for a speedy reply; I can't wait to get started! I'll try and give back if possible.

**Comment by AydinHassan** [comment]
Great - glad it's working. Feel free to get involved with anything! :)
